CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number VARCHAR(32) NOT NULL UNIQUE,
    customer_id VARCHAR(64) NOT NULL,
    issue_type VARCHAR(128) NOT NULL DEFAULT 'general',
    lob VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    assigned_queue VARCHAR(128),
    assigned_agent VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_tasks_customer_status ON tasks (customer_id, status);
CREATE INDEX idx_tasks_task_number ON tasks (task_number);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    task_id BIGINT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    sender_type VARCHAR(32) NOT NULL,
    sender_identifier VARCHAR(512) NOT NULL,
    body TEXT NOT NULL,
    attachment_json TEXT,
    external_thread_ref VARCHAR(512),
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_task FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE INDEX idx_messages_task_created ON messages (task_id, created_at);

CREATE TABLE customer_identity_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(64) NOT NULL,
    identifier_type VARCHAR(32) NOT NULL,
    identifier_value VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_identity UNIQUE (identifier_type, identifier_value)
);

CREATE INDEX idx_identity_customer ON customer_identity_links (customer_id);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(128) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id VARCHAR(128) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(256),
    payload_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE task_merge_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_task_id BIGINT NOT NULL,
    merged_task_id BIGINT NOT NULL,
    merged_at TIMESTAMP NOT NULL,
    merged_by_actor VARCHAR(256),
    CONSTRAINT uq_merge_pair UNIQUE (merged_task_id),
    CONSTRAINT fk_merge_primary FOREIGN KEY (primary_task_id) REFERENCES tasks (id),
    CONSTRAINT fk_merge_merged FOREIGN KEY (merged_task_id) REFERENCES tasks (id)
);
