CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number VARCHAR(32) NOT NULL UNIQUE,
    customer_id VARCHAR(64) NOT NULL,
    issue_type VARCHAR(128) NOT NULL DEFAULT 'general',
    lob VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    assigned_queue VARCHAR(128),
    assigned_agent VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_tickets_customer_status ON tickets (customer_id, status);
CREATE INDEX idx_tickets_ticket_number ON tickets (ticket_number);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    ticket_id BIGINT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    sender_type VARCHAR(32) NOT NULL,
    sender_identifier VARCHAR(512) NOT NULL,
    body TEXT NOT NULL,
    attachment_json TEXT,
    external_thread_ref VARCHAR(512),
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE INDEX idx_messages_ticket_created ON messages (ticket_id, created_at);

CREATE TABLE customer_identity_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(64) NOT NULL,
    identifier_type VARCHAR(32) NOT NULL,
    identifier_value VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_identity UNIQUE (identifier_type, identifier_value)
);

CREATE INDEX idx_identity_customer ON customer_identity_links (customer_id);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(128) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id VARCHAR(128) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(256),
    payload_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE ticket_merge_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_ticket_id BIGINT NOT NULL,
    merged_ticket_id BIGINT NOT NULL,
    merged_at TIMESTAMP NOT NULL,
    merged_by_actor VARCHAR(256),
    CONSTRAINT uq_merge_pair UNIQUE (merged_ticket_id),
    CONSTRAINT fk_merge_primary FOREIGN KEY (primary_ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_merge_merged FOREIGN KEY (merged_ticket_id) REFERENCES tickets (id)
);
