CREATE TABLE ticket_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    ticket_id BIGINT NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    claim_id VARCHAR(64),
    policy_id VARCHAR(64),
    document_type VARCHAR(64) NOT NULL,
    file_url VARCHAR(2048) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ticket_documents_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE INDEX idx_ticket_documents_ticket ON ticket_documents (ticket_id);
CREATE INDEX idx_ticket_documents_customer ON ticket_documents (customer_id);
CREATE INDEX idx_ticket_documents_claim ON ticket_documents (claim_id);
CREATE INDEX idx_ticket_documents_policy ON ticket_documents (policy_id);
