CREATE TABLE task_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    task_id BIGINT NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    claim_id VARCHAR(64),
    policy_id VARCHAR(64),
    document_type VARCHAR(64) NOT NULL,
    file_url VARCHAR(2048) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    metadata_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_documents_task FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE INDEX idx_task_documents_task ON task_documents (task_id);
CREATE INDEX idx_task_documents_customer ON task_documents (customer_id);
CREATE INDEX idx_task_documents_claim ON task_documents (claim_id);
CREATE INDEX idx_task_documents_policy ON task_documents (policy_id);
