CREATE TABLE customer_contact_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(512) NOT NULL,
    phone VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_contact_mapping_email UNIQUE (email),
    CONSTRAINT uq_contact_mapping_phone UNIQUE (phone)
);

CREATE INDEX idx_contact_mapping_email ON customer_contact_mappings (email);
CREATE INDEX idx_contact_mapping_phone ON customer_contact_mappings (phone);
